name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ] # 监听 main 分支

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 安装 Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # 使用 Bun 安装依赖并打包
      - name: Install and Build
        run: |
          bun install
          bun run build

      # 部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # 如果是 CRA 项目请改成 build
          branch: gh-pages
